### ISSUE TITLE
waiting for implementation to reach tip before testing

### ISSUE THREAD

**Issue by fdmirza** [coinbase/rosetta-cli#155]
**Describe the bug**
Starting today, I am getting `waiting for implementation to reach tip before testing...` for check:construction

```
020/10/07 16:17:15 0 Balances Updated
2020/10/07 16:17:15 check:construction status server running on port 9090
2020/10/07 16:17:15 waiting for implementation to reach tip before testing...
[MEMORY] Heap: 1101.724197MB Stack: 0.656250MB System: 1260.756973MB GCs: 2
[STATS] Transactions Confirmed: 0 (Created: 0, In Progress: 0, Stale: 0, Failed: 0) Addresses Created: 0
2020/10/07 16:17:25 waiting for implementation to reach tip before testing...
[MEMORY] Heap: 1101.786850MB Stack: 0.656250MB System: 1260.756973MB GCs: 2
```

**To Reproduce**
run `rosetta-cli check:construction --configuration-file <config.json>`

**Expected behavior**
It should start check:construction flow

**Additional context**
```
 "online_url": <URL>,
  "data_directory": "",
  "http_timeout": 300,
  "max_retries": 5,
  "retry_elapsed_time": 0,
  "max_online_connections": 0,
  "max_sync_concurrency": 0,
  "tip_delay": 60,
  "log_configuration": false,
  "construction": {
    "offline_url": <URL>,
    "max_offline_connections": 0,
    "stale_depth": 0,
    "broadcast_limit": 0,
    "ignore_broadcast_failures": false,
    "clear_broadcasts": false,
    "broadcast_behind_tip": false,
    "block_broadcast_limit": 0,
    "rebroadcast_all": false,
    "constructor_dsl_file": "stacks.ros",
    "end_conditions": {
      "create_account": 10,
      "transfer": 10
    }
  }
```

**Comment by patrick-ogrady** [comment]
👋  @fdmirza! Thanks for posting this issue.

This is actually the new intended behavior of `check:construction`. Prior to the latest release, we would start syncing from the latest available block (which could be very far from tip if the implementation was still syncing). This led to storing unnecessary data on disk and often increased the time to start testing (because all blocks unrelated to construction testing would need to be synced). Once you connect to an implementation that is at tip (as defined by `tip_delay`), the test should start automatically!

I see you have `stacks.ros` in your config file! I hope you are enjoying the new DSL!

**Comment by patrick-ogrady** [comment]
Received a similar question on the community: https://community.rosetta-api.org/t/ros-file-questions-in-recent-construction-api-configuration/253/2?u=patrick.ogrady
