### ISSUE TITLE
check:construction gives status in operation as empty

### ISSUE THREAD

**Issue by fdmirza** [coinbase/rosetta-cli#180]
**Describe the bug**
When I run check:construction, I get empty status in operations during /parse. 
**To Reproduce**

**Expected behavior**
It should have status defined in ros file.

**Additional context**

**Comment by patrick-ogrady** [comment]
👋  @fdmirza, sorry for the confusion!

This decision was intentional as an "intent" doesn't really have a defined "status" prior to appearing on-chain. This clarification is in our documentation backlog 😬  (I believe most of the confusion is caused by our website indicating that `Operation.Status` is always required). Another team wrote about this as one of their final blockers to getting the automated testing working: https://community.rosetta-api.org/t/construction-automated-test-account-balance-is-always-zero-for-newly-created-addresses/144/18?u=patrick.ogrady

Our `rosetta-bitcoin` example illustrates my explanation: https://github.com/coinbase/rosetta-bitcoin/blob/7e7f67e2e600e5a29dcc6f013a63a9dda30ace1f/rosetta-cli-conf/testnet/bitcoin.ros#L142-L162

Are you relying on the `Operation.Status` of the "intent" you provide during construction for something in your implementation?

**Comment by fdmirza** [comment]
Thanks @patrick-ogrady for your reply.
This is a blocker for us as well. In our implementation we have an enum for TxStatus that does not have an empty value. And we do not want to have an empty status end up in database. Is there a way to have a non-empty status.
This is the error that I am getting;
`Command Failed: Operation.Status must be empty for construction unable to parse operations: /construction/parse: unable to parse unsigned transaction: unable to create transaction`

**Comment by patrick-ogrady** [comment]
> This is a blocker for us as well. In our implementation we have an enum for TxStatus that does not have an empty value. And we do not want to have an empty status end up in database.

Could you elaborate on what you mean by "end up in database" here (your Construction API implementation should be stateless)? The transaction you construct will have a populated status when it ends up on chain (and is queried using `/block` and `/block/transaction`).

> This is the error that I am getting: `Command Failed: Operation.Status must be empty for construction unable to parse operations: /construction/parse: unable to parse unsigned transaction: unable to create transaction`

Yep! That is 100% expected. Your `/construction/parse` call should not return a populated `Operation.Status`. Here is our Bitcoin code for that endpoint: https://github.com/coinbase/rosetta-bitcoin/blob/7e7f67e2e600e5a29dcc6f013a63a9dda30ace1f/services/construction_service.go#L564-L623
