### ISSUE TITLE
Questions of rosetta-api

### ISSUE THREAD

**Issue by RainFallsSilent** [coinbase/rosetta-cli#271]
When implementing the Coinbase API, we encountered several questions:
1. How can we tell Coinbase Exchange the curve_type?
2. Completed the '/network/options' API with historical_balance_lookup been set to true. Is this a problem?

Not sure if I can find the answers here, looking forward to your answers.

**Comment by shrimalmadhur** [comment]
Hello @RainFallsSilent ,

1) You can specify the `curve_type` in the [/construction/derive](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionderive) request. We support these [curve_type](https://github.com/coinbase/rosetta-specifications/blob/master/models/CurveType.yaml) now. If your blockchain has different curve_type, then our systems have to support it if your blockchain has to be listed at Coinbase.
2) If you have `historical_balance_lookup` true, make sure you have your node supporting that since if t doesn't then rosetta-cli data check might fail reconciliation checks.

Hope that helps. Let me know if you have more questions.

**Comment by RainFallsSilent** [comment]
@shrimalmadhur  thanks a lot.
Maybe I didn't make myself clear,  we can only set `curve_type` in `/construction/derive` request, but the request will be created by Coinbase Exchange when rosetta-API server online, there is no way to tell Coinbase Exchange the `curve_type`.
Some similar parameters like `Operation.Type` and others are not informed to the client in API, but the client needs to use them when generating request. Is it ok to inform you of these parameters before going online?

**Comment by shrimalmadhur** [comment]
@RainFallsSilent So yes. if you integrate your asset with Coinbase exchange, Coinbase will take care of sending the correct `curve_type` since that is predefined for your chain. In terms of operationType that will come from [/network/options](https://www.rosetta-api.org/docs/NetworkApi.html#response-1) which will be hardcoded in your rosetta implementation.

**Comment by shrimalmadhur** [comment]
Resolving due to inactivity. Please re-open if you have any further questions.
